### PR TITLE
Fixed stylings and made everything default to dark mode.

### LINKED ISSUE #40: Dark Mode
Users should be able to switch between light and dark mode.

CSS3 variables are an option.

### PR DESCRIPTION
**Pull request by josh-velasquez**
Updates:
- Updated everything to default to dark mode
- Code formatting

### CODE REVIEW

File: client/src/components/streams/StreamShow.js [hunk 1]
```diff
@@ -49,22 +49,29 @@ class StreamShow extends React.Component {
...
-          <div className="content-scrollable">
+          <div
+            className="content-scrollable"
+            style={{ color: "white", paddingLeft: 5 }}
+          >
             <video ref={this.videoRef} style={{ width: "100%" }} controls />
-            <h1>{title}</h1>
-            <h4>#{gametag}</h4>
-            <h5>{description}</h5>
+            <div style={{ padding: 10 }}>
```
Comment (emilio-alvarez) [inline client/src/components/streams/StreamShow.js]: I think this is over-riding the default padding from semantic and making stuff look uncentered. Either that or something with line 57. The smaller gap does look better, but the username being uncentered isn't ideal.
Before:
image

After:
image

**Review by emilio-alvarez — COMMENTED** [review]
Nice! The colors look pretty nice.

Is there a reason you hard coded these into the javascript? It'd be a lot better if these were in the css file. There's a lot of reused colors that would be a pain to change if we wanted to in the future.

Also I noticed this in the edit and create stream modals. Text hasn't been converted to white.

image

Theres also this tiny gap between the sidebar and the top bar:
image

File: client/src/components/Modal.js [hunk 2]
```diff
@@ -9,14 +9,16 @@ const Modal = (props) => {
         className="ui standard modal visible active"
       >
         <div
+          id="white-text"
```
Comment (emilio-alvarez) [inline client/src/components/Modal.js]: Should these just be classes? I thought there could only be a single element with a particular id.

File: client/src/components/Header.js [hunk 3]
```diff
@@ -8,7 +8,7 @@ import Logo from "./logonobg.png";
 
 const Header = () => {
   return (
-    <div className="ui menu inverted">
+    <div className="ui menu inverted" style={{ margin: "0px 0px 2px" }}>
```
Comment (emilio-alvarez) [inline client/src/components/Header.js:11]: Hmmm is there that tiny gap from before because the header has a bottom margin of 2? Is there a reason you added this margin instead of making everything 0?

**Review by emilio-alvarez — COMMENTED** [review]
These are still black. I think they're in StreamForm.

image

The subscribe button is still aligned a bit weird. Might be more trouble than it's worth to fix at this point since i think the margins and stuff might be a little finicky. Overall it does look nice though!

File: client/src/components/Modal.js (hunk 2 above)
Comment (josh-velasquez) [reply client/src/components/Modal.js]: I tried classes but for some reason having multiple classes does not work. For example the Modal.js, I tried to have header white-text (with .white-text {colour: white} in css) it would not inherit it for some reason so I used ID instead and it seemed to work

File: client/src/components/Header.js (hunk 3 above)
Comment (josh-velasquez) [reply client/src/components/Header.js:11]: It looked weird on my monitor when it was rendered. Maybe it's just me.
